### ISSUE TITLE
Executing a test with wrong parameter type generates error 500

### ISSUE THREAD

**Issue by sunchaser68** [wavesplatform/waves-ide#236]
1) Create a RIDE method that accepts a String Parameter:

```
@Callable(i)
func bet(currencyValue: String) = {
    let WLT = base58'***'
    let account = toBase58String(i.caller.bytes)
```

2) Write a test that calls the method with a wrong type:

```
it('test_bet', async function()
{
    let dAppAddress = '***';
    let WLT = "***";
    let txObjectSigned = invokeScript({
        dApp: dAppAddress,
        call: {
            function: "bet",
            args: [
                {type:"integer", value:240}
            ]
        },
        payment: [{assetId:WLT, amount:500000}],
        fee: 900000
    })
```
3) Run the test

IDE gives Error 500. See [screenshot](https://i.imgur.com/kvJsBPv.png)

**Comment by siemarell** [comment]
Hi. Thanks for report.
I cannot 100% replicate your error(no internal server error),but there is definitely wrong behaviour: node doesn't check argument types. I've informed node team about it. You can also fill another issue in [node project](https://github.com/wavesplatform/waves).
Since this issue is not related to IDE, I'm closing it. 
If you can provide exact steps how to get 500 error, feel free to comment here, I will pass this info to node team
